"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8&1u%oz5zbs8k-(m*6k6ecpqz_dprb#u_*-81tk6=c=la)bynt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Qshop.middleware.MiddleWareTest'
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,"static"),
)
# STATIC_ROOT = os.path.join(BASE_DIR,"static") #静态文件的根目录，和STATICFILES_DIRS，MEDIA_URL，MEDIA_ROOT有冲突

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,"static")

alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA91XOUtAt6npBHAsZJbidDcBWVNGGsMN3IdoW2II23HUW+BjMSXv0LK17ZB5DgslIHDmz3+jbPVGHujJXiVoHdj6llmg3uUkOgI9QeK3pFdppLvQNv+av6JaL7wXS9bM7n0jJBqioivg5zKtcABr70cXCFD57z58U3MFVkxhxZuQx5MSpY/nJy0CTXc6g89XvZT7Vtgx0feHOwC/VBOenltVkSalcjofEjQJEQaK2yXR6EIiSSnDq8DUY3NjH6D/F5xdD1lFkc6OFZHnovi0UOaTW/63Uw5jNpa8QDCjZWj/2U5Oyw9NiWBn4EWxMk8g+D5yFVmbXwRfV9LoWekO3bQIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA91XOUtAt6npBHAsZJbidDcBWVNGGsMN3IdoW2II23HUW+BjMSXv0LK17ZB5DgslIHDmz3+jbPVGHujJXiVoHdj6llmg3uUkOgI9QeK3pFdppLvQNv+av6JaL7wXS9bM7n0jJBqioivg5zKtcABr70cXCFD57z58U3MFVkxhxZuQx5MSpY/nJy0CTXc6g89XvZT7Vtgx0feHOwC/VBOenltVkSalcjofEjQJEQaK2yXR6EIiSSnDq8DUY3NjH6D/F5xdD1lFkc6OFZHnovi0UOaTW/63Uw5jNpa8QDCjZWj/2U5Oyw9NiWBn4EWxMk8g+D5yFVmbXwRfV9LoWekO3bQIDAQABAoIBAQDuCEZorLGD1+SReJzbELEVauWq+3sE4xjkG1+hPrBNuuJAIp14mzKDTPJTiEywscYUY/QYqaFVggF90LUuGtbTlbcG6YW3a/fpAgQQIE8SGQDhjz8sUHc7AKfrgU9l5viacxIEtox+MiZuMvx3nYB8gjYmBXxidFc/nVEeH4gD2/VP328tcdntyGbgLoCXfq2SR3nczcUvYFNjEa/FNEeUmv3X1QMTFkmqNUyJzpYkdDnsas6esLG9IAK+DP+DVam+a3TZ65KQdhMzU9vcQqJNYxSe5juT8UUJyE/sYfgt9oTIiQ2NGXZTBQu8t8+6vH0+izjPkgIeswXZopsG8Z6BAoGBAP0FT+qUPw4a8cpDKhggOQjqdbOxBz118Pd4apuQMw9T2DCTecBaBX3NfaSkUdCSpd16UBGY8HCLSUyqGfENXRxuEseDHmo4yytx+bVsZj6Df0dbIPjT119zod+C+t69ELJaMBCB2zIbDNUo8Oy4vWs9MByAGvFe2kRu+/FQjnvXAoGBAPo/WwhF60eTExXUjIC/36PH2darf/JVlrDSNJZ9QuUd1P5A0ydoOrlNnVbA7H/rLEOdNxgZSArEs/LIDCE2PL94q/T2+vJz9W4rwCvZxUg0HJdMQB7Zn480uZH+hYB1grRTu1hk4S9olL1VDMsQX+383Gdt9M5q21uzCadEaZ5bAoGAEcJlsZlmM59AiWndcoQQfMe4KzypvW6h0zzofrLIYrMH4aD4Ur/+0q2xu/SsqW8hpUIIjLOnbL7aDj+CQqElf/FZ8BcL83i5CfueA1Xwd0LTlDaZQd3cqB59piqTYT70BRC/fukecY3kgLG292agJP7OebGkMnzt5Q/FL1LwLVECgYAYwTmtGNWMcAUcTLlVZyWlWvi2nqJ6g3LzrOec12lNpuTR/fGlXU8p036z/UOn58iqK5wumxmgTxMJ+jYQ9v+NZU+FXQU4BLaLnnJVJCa63MTTRqy1IIwDK5EL2ySzr2wtkHbg6KHKActs60Pntof2z+Oxq5Pi83kdmhljXYYhLwKBgEuzv+YSThs1gHkHPofrFIRkBzWir2qMFFLmgz1NtaBUXaLyPQ4+J90r5xaokHA86Yv6DNQecLaDAQ5oXvhgSsL8o5fpbAgvcZQRb3TPboHrdmjYci6VfZbk0qmOP6ogJxkRvWUJZ8OTdcC7nM0SRrkx0pUCPGt1izYQgvlDt7nS
-----END RSA PRIVATE KEY-----"""

DING_URL = "https://oapi.dingtalk.com/robot/send?access_token=43f4b33c22ae840d54ee6de90c43b6dbdd12c45b2a07686ec5820e806dd913d2"

import djcelery #导入django-celery模块
djcelery.setup_loader() #进行模块载
BROKER_URL = 'redis://127.0.0.1:6379/1' #任务容器地址，redis数据库地址
CELERY_IMPORTS = ('CeleryTask.tasks')  #具体的任务文件
CELERY_TIMEZONE = 'Asia/Shanghai' #celery时区
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler' #celey处理器，固定

from celery.schedules import crontab
from celery.schedules import timedelta

# CELERYBEAT_SCHEDULE = {
#     u'测试任务1': {
#         "task": "CeleryTask.tasks.sendDing", #任务函数
#         "schedule": timedelta(seconds=100) #执行时间
#     }
# }
ERROR_PATH = os.path.join(BASE_DIR,"error.log")
