# Generated by Django 2.1.8 on 2019-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0003_goods_goods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(default='images/default_photo', upload_to='images'),
        ),
    ]
