# Generated by Django 2.1.8 on 2019-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0004_auto_20190906_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(default='images/default_photo.jpg', upload_to='images'),
        ),
    ]
